name1 = input("What is your name? ")
gpa1 = float(input("What is your GPA? "))
name2 = input("What is your name? ")
gpa2 = float(input("What is your GPA? "))
name3 = input("What is your name? ")
gpa3 = float(input("What is your GPA? "))
name4 = input("What is your name? ")
gpa4 = float(input("What is your GPA? "))
gpaAverage = (gpa1 + gpa2 + gpa3 + gpa4 // 4)
print(name1, name2, name3, name4)